### ISSUE TITLE
Error running deploy.py with ganache-cli

### ISSUE THREAD

**Issue by ikeshare192** [PatrickAlphaC/web3_py_simple_storage#23]
The ganache UI is closed, I changed the wallet address in my_address variable to the ganache-cli address in the CLI.  
Changed the HTTPProvider to the ganache-cli loopback address "127.0.0.1:8545"
Also updated the .env vprivate key to the ganache-cli private key.  

Getting the following error:

Traceback (most recent call last):
  File "deploy.py", line 52, in <module>
    nonce = w3.eth.getTransactionCount(my_address)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/module.py", line 60, in caller
    null_result_formatters)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/providers/rpc.py", line 91, in make_request
    **self.get_request_kwargs()
  File "/opt/anaconda3/lib/python3.7/site-packages/web3/_utils/request.py", line 48, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '127.0.0.1:8545'

**Comment by ikeshare192** [comment]
disregard...I forgot to add the http:// to the address.  oops
