### ISSUE TITLE
Infura Link not working

### ISSUE THREAD

**Issue by zenc0derr** [PatrickAlphaC/web3_py_simple_storage#34]
When I'm trying to deploy the contract on Rinkeby Testnet using Infura. I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/user/Documents/Blockchain/demos/web3_py_simple_storage/deploy.py", line 39, in <module>
    nonce = w3.eth.getTransactionCount(my_address)
  File "/home/user/.local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/user/.local/lib/python3.10/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/home/user/.local/lib/python3.10/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/home/user/.local/lib/python3.10/site-packages/web3/_utils/request.py", line 103, in make_post_request
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://rinkeby.infura.io/v3/MY_INFURA_API_KEY
```

**Comment by PatrickAlphaC** [comment]
Can you try using alchemy instead? https://www.alchemy.com/

**Comment by zenc0derr** [comment]
> Can you try using alchemy instead? https://www.alchemy.com/

Thanks. Alchemy worked fine.
