### ISSUE TITLE
binascii.Error: Non-hexadecimal digit found

### ISSUE THREAD

**Issue by mitchxxmitch-code** [PatrickAlphaC/web3_py_simple_storage#7]
Traceback (most recent call last):
  File "deploy.py", line 70, in <module>
    signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/eth_account/account.py", line 727, in sign_transaction
    account = self.from_key(private_key)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/eth_account/account.py", line 250, in from_key
    key = self._parsePrivateKey(private_key)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/eth_account/account.py", line 774, in _parsePrivateKey
    return self._keys.PrivateKey(HexBytes(key))
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/hexbytes/main.py", line 23, in __new__
    bytesval = to_bytes(val)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/hexbytes/_utils.py", line 17, in to_bytes
    return hexstr_to_bytes(val)
  File "/Users/mitch/opt/anaconda3/lib/python3.8/site-packages/hexbytes/_utils.py", line 50, in hexstr_to_bytes
    return binascii.unhexlify(ascii_hex)
binascii.Error: Non-hexadecimal digit found

Maybe anyone can help me with that issue? Does anyone know how to solve it or what the problem is?

**Comment by mitchxxmitch-code** [comment]
I have found the issue, it was simply a typo! :)

**Comment by PatrickAlphaC** [comment]
Woot!

**Comment by Fabio-GitHub25** [comment]
I also had the error and I used the letter "O" instead of 0 (zero) at the beginning of the private key. But there is no "O" in hexadecimal system. That's why you should really make pauses in between haha
